spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: 
    username: admin
    password: hanafun!
    driver-class-name: com.mysql.cj.jdbc.Driver
